# Generated by Django 3.2 on 2021-05-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilis',
            options={'verbose_name': 'Profilis', 'verbose_name_plural': 'Profiliai'},
        ),
    ]
